//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemperatureConverter.TempConverter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TempConverter.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CelsiusToFarenhiet", ReplyAction="*")]
        double CelsiusToFarenhiet(double Celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CelsiusToFarenhiet", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CelsiusToFarenhietAsync(double Celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FarenhietToCelsius", ReplyAction="*")]
        double FarenhietToCelsius(double Farenhiet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FarenhietToCelsius", ReplyAction="*")]
        System.Threading.Tasks.Task<double> FarenhietToCelsiusAsync(double Farenhiet);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : TemperatureConverter.TempConverter.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<TemperatureConverter.TempConverter.WebService1Soap>, TemperatureConverter.TempConverter.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CelsiusToFarenhiet(double Celsius) {
            return base.Channel.CelsiusToFarenhiet(Celsius);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusToFarenhietAsync(double Celsius) {
            return base.Channel.CelsiusToFarenhietAsync(Celsius);
        }
        
        public double FarenhietToCelsius(double Farenhiet) {
            return base.Channel.FarenhietToCelsius(Farenhiet);
        }
        
        public System.Threading.Tasks.Task<double> FarenhietToCelsiusAsync(double Farenhiet) {
            return base.Channel.FarenhietToCelsiusAsync(Farenhiet);
        }
    }
}
