//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Addition", ReplyAction="*")]
        decimal Addition(decimal a, decimal b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Addition", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> AdditionAsync(decimal a, decimal b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtract", ReplyAction="*")]
        decimal Subtract(decimal a, decimal b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtract", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> SubtractAsync(decimal a, decimal b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplication", ReplyAction="*")]
        decimal Multiplication(decimal a, decimal b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplication", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> MultiplicationAsync(decimal a, decimal b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        decimal Division(decimal a, decimal b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> DivisionAsync(decimal a, decimal b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modules", ReplyAction="*")]
        decimal Modules(decimal a, decimal b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modules", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> ModulesAsync(decimal a, decimal b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsApplication.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication.ServiceReference1.WebService1Soap>, WindowsFormsApplication.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal Addition(decimal a, decimal b) {
            return base.Channel.Addition(a, b);
        }
        
        public System.Threading.Tasks.Task<decimal> AdditionAsync(decimal a, decimal b) {
            return base.Channel.AdditionAsync(a, b);
        }
        
        public decimal Subtract(decimal a, decimal b) {
            return base.Channel.Subtract(a, b);
        }
        
        public System.Threading.Tasks.Task<decimal> SubtractAsync(decimal a, decimal b) {
            return base.Channel.SubtractAsync(a, b);
        }
        
        public decimal Multiplication(decimal a, decimal b) {
            return base.Channel.Multiplication(a, b);
        }
        
        public System.Threading.Tasks.Task<decimal> MultiplicationAsync(decimal a, decimal b) {
            return base.Channel.MultiplicationAsync(a, b);
        }
        
        public decimal Division(decimal a, decimal b) {
            return base.Channel.Division(a, b);
        }
        
        public System.Threading.Tasks.Task<decimal> DivisionAsync(decimal a, decimal b) {
            return base.Channel.DivisionAsync(a, b);
        }
        
        public decimal Modules(decimal a, decimal b) {
            return base.Channel.Modules(a, b);
        }
        
        public System.Threading.Tasks.Task<decimal> ModulesAsync(decimal a, decimal b) {
            return base.Channel.ModulesAsync(a, b);
        }
    }
}
